// **************
// LOCALHOST 
// **************

### READ ALL from LOCALHOST
GET http://localhost:8080/students 
### READ ONE from LOCALHOST
GET http://localhost:8080/students/6260ab666e12ccf345d9a415 


### CREATE STUDENT on LOCALHOST
POST http://localhost:8080/students HTTP/1.1
content-type: application/json

{
  "firstName":"Zoey",
  "lastName":"Myers",
  "birthday":"10/10/2011",
  "beltLevel": "Blue",
  "classGroup": "Youth/Adult",
  "instructor": "David Anderson",
  "parentFirstName": "Lindsey",
  "parentLastName": "Myers"
}


### UPDATE STUDENT on LOCALHOST (Please paste in _id of correct item to update)
PUT http://localhost:8080/students/627014721bfc2d16275a765e HTTP/1.1
Content-Type: application/json

//Update belt level
{
  "firstName":"Zayden",
  "lastName":"Myers",
  "birthday":"08/12/2013",
  "beltLevel": "Blue",
  "classGroup": "Junior Samurais",
  "instructor": "Jeff Pierce",
  "parentFirstName": "Chris",
  "parentLastName": "Myers"
}

### DELETE STUDENT on LOCALHOST (Please paste in _id of correct item to delete)
DELETE http://localhost:8080/students/6260ac386e12ccf345d9a416 HTTP/1.1





// *************************
// HEROKU PRODUCTION Deploy 
// *************************

### READ ALL from HEROKU
GET https://cse341lmyersproject2.herokuapp.com/students 
### READ ONE from HEROKU
GET https://cse341lmyersproject2.herokuapp.com/students/6260ab666e12ccf345d9a415
 



### CREATE STUDENT on HEROKU
POST http://cse341lmyersproject2.herokuapp.com/students HTTP/1.1
Content-Type: application/json

{
  "firstName":"Zayden",
  "lastName":"Myers",
  "birthday":"08/12/2013",
  "beltLevel": "blue",
  "classGroup": "Junior Samurais",
  "instructor": "Jeff Pierce",
  "parentFirstName": "Chris",
  "parentLastName": "Myers"
}

### UPDATE STUDENT on HEROKU (Please paste in _id of correct item to update)
PUT http://cse341lmyersproject2.herokuapp.com/students/6260ad836e12ccf345d9a417 HTTP/1.1
Content-Type: application/json

// Update favoriteColor
{
  "firstName":"Zoey",
  "lastName":"Myers",
  "birthday":"10/10/2011",
  "beltLevel": "blue",
  "classGroup": "Youth/Adult",
  "instructor": "David Anderson",
  "parentFirstName": "Lindsey",
  "parentLastName": "Myers"
}

### DELETE STUDENT on HEROKU (Please paste in _id of correct item to delete)
DELETE http://cse341lmyersproject2.herokuapp.com/students/62674c20d86fb57c2ea15e51 HTTP/1.1
